replicaCount: 1

image:
  repository: barkinatici/ssl-expire
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ssl-expire

service:
  type: ClusterIP
  port: 2112
  targetPort: 2112

config:
  scrapeInterval: 30s
  listenAddress: ":2112"
  targets:
    - https://www.google.com
    - https://www.github.com


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
  namespace: ""
  labels:
    release: kube-prometheus-stack